# Generated by Django 4.2 on 2025-04-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_remove_question_title_alter_question_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
