# Generated by Django 4.2 on 2025-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0006_answer_author_question_author_remove_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(),
        ),
    ]
