# Generated by Django 4.2 on 2025-04-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0007_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quora_app.question'),
        ),
    ]
